// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    // Hand-written migration, so there is no scaffolded target model here — only the attributes
    // EF needs to discover it. Without this file the migration was silently skipped.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827074353_AddStockMovementDate")]
    partial class AddStockMovementDate
    {
    }
}
